# sound evaluation parameters
SAMPLERATE: 44100
TIME_SEGMENT_SIZE: 0.1
WINDOW_SIZE: 4

# output parameters
TRAIN_STEPS_PER_SAVE: 20000000
TRAIN_STEPS_PER_PRINT: 100000
NUM_REFERENCE_VECS: 4000

# model parameters
NUM_MEL_BINS: 80
HIDDEN_SIZE: 192
OUTPUT_VECTOR_SIZE: 48

# traning parameters
BATCH_SIZE: 1024
ADAM_learning_rate: 0.001

# dataset parameters
MAX_NUM_FILES: 10000

# hardware parameters
USE_GPU: True
